title: Responsive
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

baseurl: "/responsive"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
#highlighter: pygments
paginate: 3

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

google_analytics: "UA-58263416-1"
